### ISSUE TITLE
Failed to Sync (report the problem message)

### ISSUE THREAD

**Issue by gis-meta-geo** [MerginMaps/qgis-mergin-plugin#509] opened 2023-07-31 00:00 UTC
I received the following error attempting to sync from QGIS.

Traceback (most recent call last):

  File "C:\Users/adam.diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\sync_dialog.py", line 284, in pull_timer_tick
    self.pull_conflicts = pull_project_finalize(self.job)

  File "C:\Users/adam.diaz/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Mergin\mergin\client_pull.py", line 626, in pull_project_finalize
    shutil.rmtree(job.temp_dir)

  File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)

  File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())

  File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\adam.diaz\\OneDrive - Gold Road Resources\\Data_Working\\Discovery_Adam\\Mergin\\GRN_Geology\\.mergin\\fetch_v168-v174\\Extra.gpkg-diff-54f34c47-1ba2-4d89-be49-9bf1025f2e2b'

**Comment by alexbruy** [comment] 2023-09-05 15:10
Seems  duplicate of #276.

As @wonder-sk commented in the linked ticket
> it is not a good idea to have Mergin projects stored within Dropbox folder, because the sync from Dropbox interferes with the sync in Mergin, causing problems like you got. Or try pausing Dropbox sync while you sync data with Mergin.

**Closed** 2023-09-07 06:04 UTC
Labels: bug
