### ISSUE TITLE
When GeoPackage is in edit mode with pending changes and selecting Show local changes

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-mergin-plugin#432] opened 2022-06-20 08:32 UTC
...it would be good to ask user to either save or cancel changes. Currently, it does not show the pending changes made to the GeoPackage and not saved.

**Comment by ldebek** [comment] 2022-07-25 12:47
Can't reproduce this issue. It seems like it was fixed in the latest version of the plugin.
![save](https://user-images.githubusercontent.com/11883222/180780836-b5bbf4a5-9022-4efb-84fe-af49963fa5a2.PNG)

**Comment by alexbruy** [comment] 2022-09-01 10:50
Fixed with #447

**Closed by alexbruy** 2022-09-01 10:50 UTC
Labels: bug
