### ISSUE TITLE
Warning in QGIS master (3.27)

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-mergin-plugin#457] opened 2022-09-08 08:31 UTC
I get the following warnings when I run QGIS master:
```

src/core/qgsmessagelog.cpp:29 : (logMessage) [2704ms] 2022-09-08T10:29:55 Python warning[1] warning:/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py:157: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  system_version = distro.linux_distribution()[0]

traceback:  File "<string>", line 1, in <module>
  File "/home/saber/apps/QGIS/build/output/python/qgis/utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 139, in initGui
    self.post_login()
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/plugin.py", line 272, in post_login
    service_response = self.mc.user_service()
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 316, in user_service
    response = self.get("/v1/user/service")
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 207, in get
    return self._do_request(request)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 181, in wrapper
    return f(self, *args)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 190, in _do_request
    request.add_header("User-Agent", self.user_agent_info())
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Mergin/mergin/client.py", line 157, in user_agent_info
    system_version = distro.linux_distribution()[0]
  File "/usr/lib/python3/dist-packages/pip/_vendor/distro.py", line 169, in linux_distribution
    warnings.warn(
```

**Comment by wonder-sk** [comment] 2023-10-17 10:35
Duplicate of https://github.com/MerginMaps/mergin-py-client/issues/126

**Closed by wonder-sk** 2023-10-17 10:35 UTC
